version: "2"
services:

  # https://www.docker.elastic.co/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.3
    restart: always
    network_mode: host
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.3
    restart: always
    network_mode: host
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://localhost:9200